name: 627 Engine Analysis
on: pull_request

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run 627 Engine
        run: |
          python3 /Users/abhirajsingh/Downloads/627_Engine/1metis_v2pipeline/orchestrator.py \
            --repo-url ${{ github.server_url }}/${{ github.repository }} \
            --base-sha ${{ github.event.pull_request.base.sha }} \
            --head-sha ${{ github.event.pull_request.head.sha }} \
            --pr-number ${{ github.event.pull_request.number }} \
            --execution-mode graph-builder \
            --output-dir ./analysis_output \
            --backend-url https://4bc882230c57.ngrok-free.app \
            --api-key ${{ secrets.ENGINE_627_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
